services:
  postgres:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_DB: database 
      POSTGRES_USER: username 
      POSTGRES_PASSWORD: password 
    ports:
      - "5432:5432"
    network: host